name: retrowave
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.10.3
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.9
  audio_session: ^0.2.2
  path_provider: ^2.1.5
  device_info_plus: ^11.4.0
  shared_preferences: ^2.5.3
  marquee: ^2.3.0
  provider: ^6.1.5
  percent_indicator: ^4.2.5
  metadata_god: ^1.0.0
  ffmpeg_kit_flutter_new: ^1.6.1
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  introduction_screen: ^3.1.17
  lottie: ^3.3.1
  audio_service: ^0.18.18
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/lottie/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
